from .Funciones_Afirme import *
from .Funciones_BBVA import *
from .Funciones_Banorte import *
from .Funciones_BanRegio import *
from .Funciones_BanBajio import *
from .Funciones_Inbursa import *
from .Funciones_Santander import *
from .Funciones_Scotiabank import *
from .Funciones_HeyBanco import *
from .Funciones_Banamex import *
from .Funciones_Azteca import *
from .Funciones_HSBC import *
from .Funciones_MercadoPago import *
from .Funciones_Nu import *
from .Funciones_Bancoppel import *
from .Funciones_Banjercito import *