from Scraping_Bancos_MX.Funciones_Afirme import *
from Scraping_Bancos_MX.Funciones_BBVA import *
from Scraping_Bancos_MX.Funciones_Banorte import *
from Scraping_Bancos_MX.Funciones_BanRegio import *
from Scraping_Bancos_MX.Funciones_BanBajio import *
from Scraping_Bancos_MX.Funciones_Inbursa import *
from Scraping_Bancos_MX.Funciones_Santander import *
from Scraping_Bancos_MX.Funciones_Scotiabank import *
from Scraping_Bancos_MX.Funciones_HeyBanco import *
