from Funciones_Afirme import *
from Funciones_BBVA import *
from Funciones_Banorte import *
from Funciones_BanRegio import *
from Funciones_BanBajio import *
from Funciones_Inbursa import *
from Funciones_Santander import *
from Funciones_Scotiabank import *
from Funciones_HeyBanco import *
